services:
  - type: web
    name: telegram-bot-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your-telegram-bot-token-here
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com
